version: "3"
services:
  app:
    build: .
    environment:
      NODE_ENV: development
      APP_PORT: 3000
      REDIS_HOST: "REDIS_HOST_VALUE"
      BUll_REDIS_HOST: "BUll_HOST_VALUE"
      HOST: redis
      REDIS_PORT: 6379
      POSTGRES_USER: "POSTGRES_USER_VALUE"
      POSTGRES_PASSWORD: "POSTGRES_PASSWORD_VALUE"
      POSTGRES_DB: "POSTGRES_DB_VALUE"
      POSTGRES_HOST: "POSTGRES_HOST_VALUE"
      CORS_HOST: "CORS_HOST_VALUE"
      SERVICE_HOST: "SERVICE_HOST_VALUE"
      EMAIL_HOST: email-smtp.us-east-1.amazonaws.com
      EMAIL_PORT: 587
      EMAIL_USER: "SES_USER_VALUE"
      EMAIL_PSWD: "SES_PSWD_VALUE"
      EMAIL_SENDER: "SES_EMAIL_VALUE"
      SERVICE_API_HOST: "SERVICE_API_HOST_VALUE"
      SQS_JOB_HANDLER_URL: "SQS_JOB_HANDLER_URL_VALUE"
      SQS_AWS_REGION: "SQS_AWS_REGION_VALUE"
      SQS_AWS_ACCESS_KEY_ID: "SQS_AWS_ACCESS_KEY_ID_VALUE"
      SQS_AWS_SECRET_ACCESS_KEY: "SQS_AWS_SECRET_ACCESS_KEY_VALUE"
      ACTIVITY_LOG_QUEUE_URL: "ACTIVITY_LOG_QUEUE_URL_VALUE"
      COGNITO_API_VERSION: "COGNITO_API_VERSION_VALUE"
      MAIL_CONTACT_URL: "MAIL_CONTACT_URL_VALUE"
      USER_EXPIRE_AFTER_DAYS: "USER_EXPIRE_AFTER_DAYS_VALUE"
      JWT_ALG: "JWT_ALG_VALUE"
      JWT_E: "JWT_E_VALUE"
      JWT_KID: "JWT_KID_VALUE"
      JWT_KTY: "JWT_KTY_VALUE"
      JWT_N: "JWT_N_VALUE"
      JWT_USE: "JWT_USE_VALUE"
      ACCESSTOKEN_JWTKID: "ACCESSTOKEN_JWTKID_VALUE"
      ACCESSTOKEN_JWTN: "ACCESSTOKEN_JWTN_VALUE"
      OCCUPANT_EXPIRE_AFTER_DAYS: "OCCUPANT_EXPIRE_AFTER_DAYS_VALUE"
      DYNAMODB_AWS_REGION: "DYNAMODB_AWS_REGION_VALUE"
      DYNAMODB_AWS_ACCESS_KEY_ID: "DYNAMODB_AWS_ACCESS_KEY_ID_VALUE"
      DYNAMODB_AWS_SECRET_ACCESS_KEY: "DYNAMODB_AWS_SECRET_ACCESS_KEY_VALUE"
      DYNAMODB_TABLE_USERDEVICEATTRIBUTES: "DYNAMODB_TABLE_USERDEVICEATTRIBUTES_VALUE"
      DYNAMODB_TABLE_USERATTRIBUTES: "DYNAMODB_TABLE_USERATTRIBUTES_VALUE"
      DYNAMODB_TABLE_USERPERMISSIONS: "DYNAMODB_TABLE_USERPERMISSIONS_VALUE"
      DYNAMODB_TABLE_USER_GATEWAY_ATTRIBUTES: "DYNAMODB_TABLE_USER_GATEWAY_ATTRIBUTES_VALUE"
      ADMIN_EMAIL: "ADMIN_EMAIL_VALUE"
      ADMIN_PASSWORD: "ADMIN_PASSWORD_VALUE"
      ACCOUNT_ID: "ACCOUNT_ID_VALUE"
      APMINSIGHT_LICENSE_KEY: "APMINSIGHT_LICENSE_KEY_VALUE"
      APMINSIGHT_APP_NAME: "APMINSIGHT_APP_NAME_VALUE"
      APMINSIGHT_APP_PORT: "APMINSIGHT_APP_PORT_VALUE"
      DEVICE_PROVISION_URL: "DEVICE_PROVISION_URL_VALUE"
      AWS_USER_POOL_WEB_CLIENT_ID: "AWS_USER_POOL_WEB_CLIENT_ID_VALUE"
      AWS_COGNITO_REGION: "AWS_COGNITO_REGION_VALUE"
      AWS_USER_POOL_ID: "AWS_USER_POOL_ID_VALUE"
      POSTGRES_DB_POOL_MAX: "POSTGRES_DB_POOL_MAX_VALUE"
      POSTGRES_DB_POOL_MIN: "POSTGRES_DB_POOL_MIN_VALUE"
      POSTGRES_DB_POOL_ACQUIRE: "POSTGRES_DB_POOL_ACQUIRE_VALUE"
      POSTGRES_DB_POOL_IDLE_VALUE: "POSTGRES_DB_POOL_IDLE_VALUE_VALUE"
      SQS_CAMERA_DEVICE_ACTION_QUEUE_URL: "SQS_CAMERA_DEVICE_ACTION_QUEUE_URL_VALUE"
      GITLAB_TICKET_SEARCH_URL_VALUE: "GITLAB_TICKET_SEARCH_URL"
      GITLAB_TICKET_UPDATE_URL_VALUE: "GITLAB_TICKET_UPDATE_URL"
      NOTIFICATION_QUEUE_URL_VALUE: "NOTIFICATION_QUEUE_URL"
      EMAIL_QUEUE_URL_VALUE: "EMAIL_QUEUE_URL"
    ports:
      - "3000:3000"
    command: npm run dev && npm run migrate
    volumes:
      - .:/app/
      - /app/node_modules
      - /home/ec2-user/logs:/usr/src/app/logs
    logging:
      driver: "awslogs"
      options:
        awslogs-region: "REGION_CLOUDWATCH"
        awslogs-group: "/service-api/LOG_PATH_VALUE/app.log"
