const ErrorCodes = Object.freeze({
  '000001': {
    responseCode: '000001',
    text: 'COMPANY_NOT_FOUND',
    statusCode: 404,
    http_status_text: 'NOT_FOUND',
    message: 'Company not found',
    type: 'UleecoClientError',
    module: 'COMPANIES',
  },
  '000002': {
    responseCode: '000002',
    text: 'COMPANY_CODE_EXISTS',
    statusCode: 422,
    http_status_text: 'COMPANY_CODE_EXISTS',
    message: 'Company code already exists',
    type: 'UleecoClientError',
    module: 'COMPANIES',
  },
  '000003': {
    responseCode: '000003',
    text: 'COMPANY_ID_NOT_FOUND',
    statusCode: 404,
    http_status_text: 'NOT_FOUND',
    message: 'Company id not found to delete',
    type: 'UleecoClientError',
    module: 'COMPANIES',
  },
  '000004': {
    responseCode: '000004',
    text: 'COMPANY_ID_NOT_FOUND',
    statusCode: 404,
    http_status_text: 'NOT_FOUND',
    message: 'Company id not found to update',
    type: 'UleecoClientError',
    module: 'COMPANIES',
  },
  '000005': {
    responseCode: '000005',
    text: 'COMPANY_EXCEL_NOT_ATTACHED',
    statusCode: 400,
    http_status_text: 'EXCEL_NOT_ATTACHED',
    message: 'Company excel is not attached as multipart',
    type: 'UleecoClientError',
    module: 'COMPANIES',
  },
  '000006': {
    responseCode: '000006',
    text: 'COMPANIES_NOT_FOUND',
    statusCode: 400,
    http_status_text: 'NOT_FOUND',
    message: 'No companies found',
    type: 'UleecoClientError',
    module: 'COMPANIES',
  },
  '000007': {
    responseCode: '000007',
    text: 'LOCATION_NOT_CREATED ',
    statusCode: 422,
    http_status_text: 'VALIDATION_ERROR',
    message: 'Location not created',
    type: 'UleecoServerError',
    module: 'COMPANIES',
  },
  '000008': {
    responseCode: '000008',
    text: 'COMPANY_NOT_FOUND',
    statusCode: 404,
    http_status_text: 'NOT_FOUND',
    message: 'x-company-code missing in headers',
    type: 'UleecoClientError',
    module: 'COMPANIES',
  },
  100000: {
    responseCode: '100000',
    text: 'CORE_PERMISSION_MAPPINGS_NOT_FOUND',
    statusCode: 404,
    http_status_text: 'NOT_FOUND',
    message: 'Core permissions mapping for company not found',
    type: 'UleecoClientError',
    module: 'CORE_PERMISSION_MAPPINGS',
  },
  100001: {
    responseCode: '100001',
    text: 'CORE_PERMISSION_MAPPING_ALREADY_EXISTS',
    statusCode: 422,
    http_status_text: 'ALREADY_EXISTS',
    message: 'Core permissions mapping for company already exists',
    type: 'UleecoClientError',
    module: 'CORE_PERMISSION_MAPPINGS',
  },
  100002: {
    responseCode: '100002',
    text: 'CORE_PERMISSION_MAPPING_ID_NOT_FOUND',
    statusCode: 404,
    http_status_text: 'NOT_FOUND',
    message: 'Core permissions mapping id to delete not found',
    type: 'UleecoClientError',
    module: 'CORE_PERMISSION_MAPPINGS',
  },
  200000: {
    responseCode: '200000',
    text: 'INVITATIONS_NOT_FOUND',
    statusCode: 404,
    http_status_text: 'NOT_FOUND',
    message: 'Invitations for company not found',
    type: 'UleecoClientError',
    module: 'INVITATIONS',
  },
  200001: {
    responseCode: '200001',
    text: 'INVITATION_EMAIL_ALREADY_EXISTS',
    statusCode: 422,
    http_status_text: 'EMAIL_ALREADY_EXISTS',
    message: 'Invitation cannot be created email already exists',
    type: 'UleecoClientError',
    module: 'INVITATIONS',
  },
  200002: {
    responseCode: '200002',
    text: 'INVITATION_ID_EXPIRE_NOT_FOUND',
    statusCode: 404,
    http_status_text: 'NOT_FOUND',
    message: 'Invitation id not found to expire',
    type: 'UleecoClientError',
    module: 'INVITATIONS',
  },
  200003: {
    responseCode: '200003',
    text: 'INVITATION_ID_ACCEPT_NOT_FOUND',
    statusCode: 404,
    http_status_text: 'NOT_FOUND',
    message: 'Invitation id not found to accept',
    type: 'UleecoClientError',
    module: 'INVITATIONS',
  },
  200004: {
    responseCode: '200004',
    text: 'INVITATION_ID_DELETE_NOT_FOUND',
    statusCode: 404,
    http_status_text: 'NOT_FOUND',
    message: 'Invitation id not found to delete',
    type: 'UleecoClientError',
    module: 'INVITATIONS',
  },
  200005: {
    responseCode: '200005',
    text: 'INVITATION_ID_RESEND_NOT_FOUND',
    statusCode: 404,
    http_status_text: 'NOT_FOUND',
    message: 'Invitation id not found to resend',
    type: 'UleecoClientError',
    module: 'INVITATIONS',
  },
  200006: {
    responseCode: '200006',
    text: 'EDIT_INVITATION_PERMISSION_BODY_INVALID',
    statusCode: 422,
    http_status_text: 'INVALID_BODY',
    message: 'Invitation edit permission should contain site_permission or core_permission',
    type: 'UleecoClientError',
    module: 'INVITATIONS',
  },
  200007: {
    responseCode: '200007',
    text: 'EDIT_INVITATION_PERMISSION_ID_NOT_FOUND',
    statusCode: 404,
    http_status_text: 'NOT_FOUND',
    message: 'Invitation id to edit not found',
    type: 'UleecoClientError',
    module: 'INVITATIONS',
  },
  200008: {
    responseCode: '200008',
    text: 'EDIT_INVITATION_ALREADY_ACCEPTED',
    statusCode: 422,
    http_status_text: 'ALREADY_EXISTS',
    message: 'Invitation id already accepted can\'t edit',
    type: 'UleecoClientError',
    module: 'INVITATIONS',
  },
  200009: {
    responseCode: '200009',
    text: 'USER_CANNOT_SEND_INVITATION_HIMSELF',
    statusCode: 422,
    http_status_text: 'EMAIL_ALREADY_EXISTS',
    message: 'User cannot send invitation to himself',
    type: 'UleecoClientError',
    module: 'INVITATIONS',
  },
  300000: {
    responseCode: '300000',
    text: 'CORE_PERMISSIONS_NOT_FOUND',
    statusCode: 404,
    http_status_text: 'NOT_FOUND',
    message: 'Core permissions for company not found',
    type: 'UleecoClientError',
    module: 'CORE_PERMISSIONS',
  },
  300001: {
    responseCode: '300001',
    text: 'CORE_PERMISSION_NOT_CREATED',
    statusCode: 400,
    http_status_text: 'BAD_REQUEST',
    message: 'Core permission not configured',
    type: 'UleecoClientError',
    module: 'CORE_PERMISSIONS',
  },
  300002: {
    responseCode: '300002',
    text: 'CORE_PERMISSION_NOT_FOUND',
    statusCode: 404,
    http_status_text: 'NOT_FOUND',
    message: 'Core permission id not found',
    type: 'UleecoClientError',
    module: 'CORE_PERMISSIONS',
  },
  300003: {
    responseCode: '300002',
    text: 'CORE_PERMISSION_USER_NOT_FOUND',
    statusCode: 404,
    http_status_text: 'NOT_FOUND',
    message: 'Core permission for user not found',
    type: 'UleecoClientError',
    module: 'CORE_PERMISSIONS',
  },
  300004: {
    responseCode: '300004',
    text: 'CORE_PERMISSION_DELETE_NOT_FOUND',
    statusCode: 404,
    http_status_text: 'NOT_FOUND',
    message: 'Core permission id to delete not found',
    type: 'UleecoClientError',
    module: 'CORE_PERMISSIONS',
  },
  400000: {
    responseCode: '400000',
    text: 'LOCATION_TYPE_EXISTS',
    statusCode: 422,
    http_status_text: 'UNPROCESSABLE_ENTITY',
    message: 'Location type already exists',
    type: 'UleecoClientError',
    module: 'LOCATION_TYPES',
  },
  400001: {
    responseCode: '400001',
    text: 'LOCATION_TYPES_NOT_FOUND',
    statusCode: 404,
    http_status_text: 'NOT_FOUND',
    message: 'Location types for company not found',
    type: 'UleecoClientError',
    module: 'LOCATION_TYPES',
  },
  400002: {
    responseCode: '400002',
    text: 'LOCATION_TYPES_ID_NOT_FOUND',
    statusCode: 404,
    http_status_text: 'NOT_FOUND',
    message: 'Location types id for company not found',
    type: 'UleecoClientError',
    module: 'LOCATION_TYPES',
  },
  400003: {
    responseCode: '400003',
    text: 'LOCATION_TYPES_ID_DELETE_NOT_FOUND',
    statusCode: 404,
    http_status_text: 'NOT_FOUND',
    message: 'Location types id to delete not found',
    type: 'UleecoClientError',
    module: 'LOCATION_TYPES',
  },
  400004: {
    responseCode: '400004',
    text: 'LOCATION_TYPES_ID_UPDATE_NOT_FOUND',
    statusCode: 404,
    http_status_text: 'NOT_FOUND',
    message: 'Location types id to update not found',
    type: 'UleecoClientError',
    module: 'LOCATION_TYPES',
  },
  500000: {
    responseCode: '500000',
    text: 'LOCATIONS_NOT_FOUND',
    statusCode: 404,
    http_status_text: 'NOT_FOUND',
    message: 'Locations for company not found',
    type: 'UleecoClientError',
    module: 'LOCATIONS',
  },
  500001: {
    responseCode: '500001',
    text: 'LOCATION_EXISTS',
    statusCode: 422,
    http_status_text: 'UNPROCESSABLE_ENTITY',
    message: 'Location already exists',
    type: 'UleecoClientError',
    module: 'LOCATIONS',
  },
  500002: {
    responseCode: '500002',
    text: 'LOCATION_NOT_FOUND',
    statusCode: 404,
    http_status_text: 'NOT_FOUND',
    message: 'Location id not found',
    type: 'UleecoClientError',
    module: 'LOCATIONS',
  },
  500003: {
    responseCode: '500003',
    text: 'LOCATION_DELETE_NOT_FOUND',
    statusCode: 404,
    http_status_text: 'NOT_FOUND',
    message: 'Location id to delete not found',
    type: 'UleecoClientError',
    module: 'LOCATIONS',
  },
  500004: {
    responseCode: '500004',
    text: 'LOCATION_UPDATE_NOT_FOUND',
    statusCode: 404,
    http_status_text: 'NOT_FOUND',
    message: 'Location id to update not found',
    type: 'UleecoClientError',
    module: 'LOCATIONS',
  },
  500005: {
    responseCode: '500005',
    text: 'CSV_FILE_UNDEFINED',
    statusCode: 400,
    http_status_text: 'UNDEFINED',
    message: 'Please upload a CSV file',
    type: 'UleecoClientError',
    module: 'LOCATIONS',
  },
  500006: {
    responseCode: '500006',
    text: 'CSV_FILE_NOT_VALIDATE',
    statusCode: 422,
    http_status_text: 'VALIDATION_ERROR',
    message: 'Please send valid data',
    type: 'UleecoClientError',
    module: 'LOCATIONS',
  },
  600000: {
    responseCode: '600000',
    text: 'ADDRESS_GENERAL_ERROR',
    statusCode: 422,
    http_status_text: 'UNPROCESSABLE_ENTITY',
    message: 'Address general error',
    type: 'UleecoClientError',
    module: 'ADDRESSES',
  },
  600001: {
    responseCode: '600001',
    text: 'ADDRESSES_NOT_FOUND',
    statusCode: 404,
    http_status_text: 'NOT_FOUND',
    message: 'Addresses not found',
    type: 'UleecoClientError',
    module: 'ADDRESSES',
  },
  600002: {
    responseCode: '600002',
    text: 'ADDRESS_ID_NOT_FOUND',
    statusCode: 404,
    http_status_text: 'NOT_FOUND',
    message: 'Address id not found',
    type: 'UleecoClientError',
    module: 'ADDRESSES',
  },
  600003: {
    responseCode: '600003',
    text: 'ADDRESS_ID_DELETE_NOT_FOUND',
    statusCode: 404,
    http_status_text: 'NOT_FOUND',
    message: 'Address id to delete not found',
    type: 'UleecoClientError',
    module: 'ADDRESSES',
  },
  600004: {
    responseCode: '600004',
    text: 'ADDRESS_ID_UPDATE_NOT_FOUND',
    statusCode: 404,
    http_status_text: 'NOT_FOUND',
    message: 'Address id to update not found',
    type: 'UleecoClientError',
    module: 'ADDRESSES',
  },
  700000: {
    responseCode: '700000',
    text: 'PERMISSION_ID_NOT_FOUND',
    statusCode: 404,
    http_status_text: 'NOT_FOUND',
    message: 'Permissions id not found',
    type: 'UleecoClientError',
    module: 'PERMISSIONS',
  },
  700001: {
    responseCode: '700001',
    text: 'PERMISSION_INVITE_NOT_FOUND',
    statusCode: 404,
    http_status_text: 'NOT_FOUND',
    message: 'Permissions invite to create permission not found',
    type: 'UleecoClientError',
    module: 'PERMISSIONS',
  },
  700002: {
    responseCode: '700002',
    text: 'PERMISSION_NOT_CREATED',
    statusCode: 422,
    http_status_text: 'UNPROCESSABLE_ENTITY',
    message: 'Permissions not created',
    type: 'UleecoServerError',
    module: 'PERMISSIONS',
  },
  700003: {
    responseCode: '700003',
    text: 'LOCATION_PERMISSIONS_NOT_FOUND',
    statusCode: 404,
    http_status_text: 'NOT_FOUND',
    message: 'Location permission not found',
    type: 'UleecoClientError',
    module: 'PERMISSIONS',
  },
  700004: {
    responseCode: '700004',
    text: 'INVITE_PERMISSION_EXISTS',
    statusCode: 422,
    http_status_text: 'UNPROCESSABLE_ENTITY',
    message: 'Location permission not found',
    type: 'UleecoClientError',
    module: 'PERMISSIONS',
  },
  800001: {
    responseCode: '800001',
    text: 'DEVICES_NOT_FOUND_FOR_LOCATION',
    statusCode: 404,
    http_status_text: 'NOT_FOUND',
    message: 'Devices not found for location',
    type: 'UleecoClientError',
    module: 'DEVICES',
  },
  800002: {
    responseCode: '800002',
    text: 'DEVICES_NOT_FOUND',
    statusCode: 404,
    http_status_text: 'NOT_FOUND',
    message: 'Devices not found',
    type: 'UleecoClientError',
    module: 'DEVICES',
  },
  800003: {
    responseCode: '800003',
    text: 'DEVICES_ID_NOT_FOUND',
    statusCode: 404,
    http_status_text: 'NOT_FOUND',
    message: 'Device id not found',
    type: 'UleecoClientError',
    module: 'DEVICES',
  },
  800004: {
    responseCode: '800004',
    text: 'DEVICE_ID_DELETE_NOT_FOUND',
    statusCode: 404,
    http_status_text: 'NOT_FOUND',
    message: 'Device id  to delete not found',
    type: 'UleecoClientError',
    module: 'DEVICES',
  },
  800005: {
    responseCode: '800005',
    text: 'DEVICE_ID_UPDATE_NOT_FOUND',
    statusCode: 404,
    http_status_text: 'NOT_FOUND',
    message: 'Device id  to update not found',
    type: 'UleecoClientError',
    module: 'DEVICES',
  },
  800006: {
    responseCode: '800006',
    text: 'DEVICE_NOT_LINKED_TO_LOCATION',
    statusCode: 422,
    http_status_text: 'UNPROCESSABLE_ENTITY',
    message: 'Device cannot be linked to location',
    type: 'UleecoClientError',
    module: 'DEVICES',
  },
  8000061: {
    responseCode: '8000061',
    text: 'LINKED_DEVICE_NOT_LINKED_TO_LOCATION',
    statusCode: 422,
    http_status_text: 'UNPROCESSABLE_ENTITY',
    message: 'LINKED Device cannot be linked to location',
    type: 'UleecoClientError',
    module: 'DEVICES',
  },
  800008: {
    responseCode: '800008',
    text: 'DEVICE_NOT_CREATED',
    statusCode: 422,
    http_status_text: 'UNPROCESSABLE_ENTITY',
    message: 'Value too long for type character varying(255)',
    type: 'UleecoClientError',
    module: 'DEVICES',
  },
  800009: {
    responseCode: '800009',
    text: 'DEVICE_BODY_VALIDATION_ERROR',
    statusCode: 422,
    http_status_text: 'UNPROCESSABLE_ENTITY',
    message: 'Request body not supported',
    type: 'UleecoClientError',
    module: 'DEVICES',
  },
  800010: {
    responseCode: '800010',
    text: 'DEVICE_LINK_ERROR',
    statusCode: 422,
    http_status_text: 'UNPROCESSABLE_ENTITY',
    message: 'Gateway cannot be linked to another gateway',
    type: 'UleecoClientError',
    module: 'DEVICES',
  },
  800011: {
    responseCode: '800011',
    text: 'DEVICE_LINK_ERROR',
    statusCode: 422,
    http_status_text: 'UNPROCESSABLE_ENTITY',
    message: 'Device cannot be linked to another device',
    type: 'UleecoClientError',
    module: 'DEVICES',
  },
  800012: {
    responseCode: '800012',
    text: 'DEVICE_TYPES_NOT_FOUND',
    statusCode: 404,
    http_status_text: 'NOT_FOUND',
    message: 'Device types not found',
    type: 'UleecoClientError',
    module: 'DEVICES',
  },
  800013: {
    responseCode: '800013',
    text: 'GATEWAY_NOT_FOUND',
    statusCode: 422,
    http_status_text: 'NOT_FOUND',
    message: 'Gateway not found',
    type: 'UleecoClientError',
    module: 'DEVICES',
  },
  800014: {
    responseCode: '800014',
    text: 'DEVICES_NOT_CREATED',
    statusCode: 422,
    http_status_text: 'NOT_FOUND',
    message: 'Devices not created',
    type: 'UleecoServerError',
    module: 'DEVICES',
  },
  800015: {
    responseCode: '800015',
    text: 'DEVICES_NOT_UPDATED',
    statusCode: 422,
    http_status_text: 'NOT_FOUND',
    message: 'Devices not updated',
    type: 'UleecoServerError',
    module: 'DEVICES',
  },
  800016: {
    responseCode: '800016',
    text: 'CSV_FILE_UNDEFINED',
    statusCode: 400,
    http_status_text: 'UNDEFINED',
    message: 'Please upload a CSV file',
    type: 'UleecoClientError',
    module: 'DEVICES',
  },
  800017: {
    responseCode: '800017',
    text: 'CSV_FILE_NOT_VALIDATE',
    statusCode: 422,
    http_status_text: 'VALIDATION_ERROR',
    message: 'Please send valid data',
    type: 'UleecoClientError',
    module: 'DEVICES',
  },
  800018: {
    responseCode: '800018',
    text: 'DEVICE_ALREADY_EXISTS',
    statusCode: 422,
    http_status_text: 'UNPROCESSABLE_ENTITY',
    message: 'Device already exists',
    type: 'UleecoClientError',
    module: 'DEVICES',
  },
  800019: {
    responseCode: '800019',
    text: 'DEVICE_NOT_FOUND',
    statusCode: 422,
    http_status_text: 'UNPROCESSABLE_ENTITY',
    message: 'Device Not Found',
    type: 'UleecoClientError',
    module: 'DEVICES',
  },
  800020: {
    responseCode: '800020',
    text: 'DEVICE_ID_NOT_FOUND',
    statusCode: 422,
    http_status_text: 'UNPROCESSABLE_ENTITY',
    message: 'Device Id Not Found',
    type: 'UleecoClientError',
    module: 'DEVICES',
  },
  800021: {
    responseCode: '800021',
    text: 'GATEWAY_DELETE_ERROR',
    statusCode: 422,
    http_status_text: 'UNPROCESSABLE_ENTITY',
    message: 'Gateway Delete Error',
    type: 'UleecoServerError',
    module: 'DEVICES',
  },
  800022: {
    responseCode: '800022',
    text: 'SHADOW_NOT_UPDATED',
    statusCode: 422,
    http_status_text: 'UNPROCESSABLE_ENTITY',
    message: 'Shadow not updated',
    type: 'UleecoServerError',
    module: 'DEVICES',
  },
  800023: {
    responseCode: '800023',
    text: 'ACTIVITY_LOGS_DELETE_ERROR',
    statusCode: 422,
    http_status_text: 'UNPROCESSABLE_ENTITY',
    message: 'Activity logs delete error',
    type: 'UleecoServerError',
    module: 'DEVICES',
  },
  800024: {
    responseCode: '800024',
    text: 'OCCUPANTS_DASHBOARD_ATTRIBUTES_DELETE_ERROR',
    statusCode: 422,
    http_status_text: 'UNPROCESSABLE_ENTITY',
    message: 'Occupants dashboard attributes delete error',
    type: 'UleecoServerError',
    module: 'DEVICES',
  },
  800026: {
    responseCode: '800026',
    text: 'DEVICE_REFERENCES_DELETE_ERROR',
    statusCode: 422,
    http_status_text: 'UNPROCESSABLE_ENTITY',
    message: 'Device references delete error',
    type: 'UleecoServerError',
    module: 'DEVICES',
  },
  800027: {
    responseCode: '800027',
    text: 'DEVICE_SCHEDULES_DELETE_ERROR',
    statusCode: 422,
    http_status_text: 'UNPROCESSABLE_ENTITY',
    message: 'Device schedules delete error',
    type: 'UleecoServerError',
    module: 'DEVICES',
  },
  800028: {
    responseCode: '800028',
    text: 'DEVICE_DELETE_ERROR',
    statusCode: 422,
    http_status_text: 'UNPROCESSABLE_ENTITY',
    message: 'Device delete error',
    type: 'UleecoServerError',
    module: 'DEVICES',
  },
  800029: {
    responseCode: '800029',
    text: 'OCCUPANT_GROUPS_DEVICES_DELETE_ERROR',
    statusCode: 422,
    http_status_text: 'UNPROCESSABLE_ENTITY',
    message: 'Occupant groups devices delete error',
    type: 'UleecoServerError',
    module: 'DEVICES',
  },
  800030: {
    responseCode: '800030',
    text: 'PREDEFINED_RULES_DELETE_ERROR',
    statusCode: 422,
    http_status_text: 'UNPROCESSABLE_ENTITY',
    message: 'Predefined rules delete error',
    type: 'UleecoServerError',
    module: 'DEVICES',
  },
  800031: {
    responseCode: '800031',
    text: 'DEVICE_ALERTS_DELETE_ERROR',
    statusCode: 422,
    http_status_text: 'UNPROCESSABLE_ENTITY',
    message: 'Device alerts delete error',
    type: 'UleecoServerError',
    module: 'DEVICES',
  },
  800032: {
    responseCode: '800032',
    text: 'ALERT_COMMUNICATION_CONFIGS_ERROR',
    statusCode: 422,
    http_status_text: 'UNPROCESSABLE_ENTITY',
    message: 'Alert communication configs delete error',
    type: 'UleecoServerError',
    module: 'DEVICES',
  },
  800034: {
    responseCode: '800034',
    text: 'DEVICE_EVENTS_DELETE_ERROR',
    statusCode: 422,
    http_status_text: 'UNPROCESSABLE_ENTITY',
    message: 'Device Events Delete Error',
    type: 'UleecoServerError',
    module: 'DEVICES',
  },
  800035: {
    responseCode: '800035',
    text: 'GATEWAY_DELETE_ERROR',
    statusCode: 422,
    http_status_text: 'UNPROCESSABLE_ENTITY',
    message: 'Gateway cannot be Deleted by this api',
    type: 'UleecoClientError',
    module: 'DEVICES',
  },
  800036: {
    responseCode: '800036',
    text: 'DEVICE_NOT_FOUND',
    statusCode: 422,
    http_status_text: 'UNPROCESSABLE_ENTITY',
    type: 'UleecoClientError',
    module: 'DEVICES',
  },
  800037: {
    responseCode: '800037',
    text: 'OCCUPANT_GROUPS_DEVICES_NOT_FOUND',
    statusCode: 400,
    http_status_text: 'UNPROCESSABLE_ENTITY',
    message: 'Occupant groups devices not found',
    type: 'UleecoClientError',
    module: 'DEVICES',
  },
  900000: {
    responseCode: '900000',
    text: 'USER_NOT_CREATED',
    statusCode: 422,
    http_status_text: 'UNPROCESSABLE_ENTITY',
    message: 'User already exists',
    type: 'UleecoClientError',
    module: 'USERS',
  },
  900001: {
    responseCode: '900001',
    text: 'USER_COGNITO_NOT_FOUND',
    statusCode: 404,
    http_status_text: 'NOT_FOUND',
    message: 'User with cognito id not found',
    type: 'UleecoClientError',
    module: 'USERS',
  },
  900003: {
    responseCode: '900003',
    text: 'USER_NOT_CREATED_INVITE_EXPIRED',
    statusCode: 422,
    http_status_text: 'UNPROCESSABLE_ENTITY',
    message: 'User Invite Expired',
    type: 'UleecoClientError',
    module: 'USERS',
  },
  900004: {
    responseCode: '900004',
    text: 'USER_ID_NOT_FOUND',
    statusCode: 404,
    http_status_text: 'NOT_FOUND',
    message: 'User id not found for deletion',
    type: 'UleecoClientError',
    module: 'USERS',
  },
  900005: {
    responseCode: '900005',
    text: 'USER_EMAIL_NOT_FOUND',
    statusCode: 404,
    http_status_text: 'NOT_FOUND',
    message: 'User id not found for updating attributes',
    type: 'UleecoClientError',
    module: 'USERS',
  },
  900006: {
    responseCode: '900006',
    text: 'DEVICE_ID_VALIDATION',
    statusCode: 422,
    http_status_text: 'UNPROCESSABLE_ENTITY',
    message: 'Request device id not supported',
    type: 'UleecoClientError',
    module: 'DEVICES',
  },
  900007: {
    responseCode: '900001',
    text: 'USER_EMAIL_PASSWORD_INCORRECT',
    statusCode: 422,
    http_status_text: 'NOT_FOUND',
    message: 'Email or password is incorrect',
    type: 'UleecoClientError',
    module: 'USERS',
  },
  900008: {
    responseCode: '900008',
    text: 'UN_AUTHORIZED',
    statusCode: 401,
    http_status_text: 'NOT_AUTHORIZED',
    message: 'Not authorized',
    type: 'UleecoClientError',
    module: 'USERS',
  },
  900009: {
    responseCode: '900009',
    text: 'UN_AUTHORIZED',
    statusCode: 401,
    http_status_text: 'NOT_AUTHORIZED',
    message: 'Invalid access token',
    type: 'UleecoClientError',
    module: 'USERS',
  },
  900010: {
    responseCode: '900010',
    text: 'NOT_FOUND',
    statusCode: 404,
    http_status_text: 'NOT_FOUND',
    message: 'User not found',
    type: 'UleecoClientError',
    module: 'USERS',
  },
  900011: {
    responseCode: '900011',
    text: 'UNPROCESSABLE_ENTITY',
    statusCode: 404,
    http_status_text: 'UNPROCESSABLE_ENTITY',
    message: 'Error while accessing the apis',
    type: 'UleecoServerError',
    module: 'USERS',
  },
  900012: {
    responseCode: '900012',
    text: 'COGNITO_USER_NOT_DELETED',
    statusCode: 422,
    http_status_text: 'UNPROCESSABLE_ENTITY',
    message: 'User from cognito not deleted',
    type: 'UleecoServerError',
    module: 'Cognito',
  },
  110000: {
    responseCode: '110000',
    text: 'STATUS_ALREADY_EXISTS',
    statusCode: 422,
    http_status_text: 'UNPROCESSABLE_ENTITY',
    message: 'Latest status already exists',
    type: 'UleecoClientError',
    module: 'OCCUPANTS',
  },
  130000: {
    responseCode: '130000',
    text: 'MODEL_ALREADY_EXISTS',
    statusCode: 422,
    http_status_text: 'UNPROCESSABLE_ENTITY',
    message: 'Model already exists',
    type: 'UleecoClientError',
    module: 'MODELS',
  },
  130001: {
    responseCode: '130001',
    text: 'MODEL_ID_NOT_FOUND',
    statusCode: 404,
    http_status_text: 'NOT_FOUND',
    message: 'Model id not found for updating attributes',
    type: 'UleecoClientError',
    module: 'MODELS',
  },
  140000: {
    responseCode: '140000',
    text: 'UNPROCESSABLE_ENTITY',
    statusCode: 403,
    http_status_text: 'UNPROCESSABLE_ENTITY',
    message: 'User not authorized to access this resource',
    type: 'UleecoClientError',
    module: 'DEVICES',
  },
  150001: {
    responseCode: '150001',
    text: 'LOCATION_ID_NOT_FOUND',
    statusCode: 422,
    http_status_text: 'UNPROCESSABLE_ENTITY',
    message: 'Location id not present in request body',
    type: 'UleecoClientError',
    module: 'DEVICES',
  },
  150002: {
    responseCode: '150002',
    text: 'GATEWAY_NOT_FOUND',
    statusCode: 422,
    http_status_text: 'DEVICE_NOT_ATTACHED_TO_GATEWAY',
    message: 'Device not attached to any gateway',
    type: 'UleecoClientError',
    module: 'DEVICES',
  },
  150003: {
    responseCode: '150003',
    text: 'INVALID_LOCATION_ID',
    statusCode: 422,
    http_status_text: 'LOCATION_NOT_FOUND_WITH_ID',
    message: 'Location not found',
    type: 'UleecoClientError',
    module: 'DEVICES',
  },
  150004: {
    responseCode: '150004',
    text: 'GATEWAYS_ID_NOT_PROVIDED',
    statusCode: 400,
    http_status_text: 'GATEWAYS_ID_MISSING_IN_REQUEST',
    message: 'Ids not provided in request body',
    type: 'UleecoClientError',
    module: 'DEVICES',
  },
  150005: {
    responseCode: '150005',
    text: 'SECONDARY_LOCATIONS_NOT_FOUND',
    statusCode: 404,
    http_status_text: 'SECONDARY_LOCATIONS_NOT_FOUND',
    message: 'Secondary locations not found for the device',
    type: 'UleecoClientError',
    module: 'DEVICES',
  },
  150006: {
    responseCode: '150006',
    text: 'NO_LOCATION_PERMISSIONS_FOUND',
    statusCode: 404,
    http_status_text: 'NO_LOCATION_PERMISSIONS_FOUND',
    message: 'NO PERMISSIONS FOUND',
    type: 'UleecoClientError',
    module: 'PERMISSIONS',
  },
  150008: {
    responseCode: '150008',
    text: 'ERROR_LOCATION_PERMISSIONS_DELETION',
    statusCode: 422,
    http_status_text: 'ERROR_LOCATION_PERMISSIONS_DELETION',
    message: 'ERROR_LOCATION_PERMISSIONS_DELETION',
    type: 'UleecoServerError',
    module: 'PERMISSIONS',
  },
  160000: {
    responseCode: '160000',
    text: 'OCCUPANT_ALREADY_EXISTS',
    statusCode: 422,
    http_status_text: 'UNPROCESSABLE_ENTITY',
    message: 'Occupant already exists',
    type: 'UleecoClientError',
    module: 'OCCUPANT',
  },
  160001: {
    responseCode: '160001',
    text: 'LOCATION_NOT_FOUND',
    statusCode: 404,
    http_status_text: 'NOT_FOUND',
    message: 'Location id not found',
    type: 'UleecoClientError',
    module: 'OCCUPANT',
  },
  160002: {
    responseCode: '160002',
    text: 'OCCUPANT_NOT_FOUND',
    statusCode: 404,
    http_status_text: 'NOT_FOUND',
    message: 'Occupant id not found',
    type: 'UleecoClientError',
    module: 'OCCUPANT',
  },
  160005: {
    responseCode: '160005',
    text: 'INVITATION_ID_RESEND_NOT_FOUND',
    statusCode: 404,
    http_status_text: 'NOT_FOUND',
    message: 'Invitation id not found to resend',
    type: 'UleecoClientError',
    module: 'OCCUPANT',
  },
  160006: {
    responseCode: '160006',
    text: 'INVITATION_ID_DELETE_NOT_FOUND',
    statusCode: 404,
    http_status_text: 'NOT_FOUND',
    message: 'Invitation id not found to delete',
    type: 'UleecoClientError',
    module: 'OCCUPANT',
  },
  160007: {
    responseCode: '160007',
    text: 'OCCUPANT_ID_NOT_FOUND',
    statusCode: 404,
    http_status_text: 'NOT_FOUND',
    message: 'Occupant id not found',
    type: 'UleecoClientError',
    module: 'OCCUPANT',
  },
  160008: {
    responseCode: '160008',
    text: 'OCCUPANT_ID_DELETE_NOT_FOUND',
    statusCode: 404,
    http_status_text: 'NOT_FOUND',
    message: 'Occupant id not found to delete',
    type: 'UleecoClientError',
    module: 'OCCUPANT',
  },
  160009: {
    responseCode: '160009',
    text: 'INVITATION_ALREADY_SENT_TO_THE_USER',
    statusCode: 422,
    http_status_text: 'UNPROCESSABLE_ENTITY',
    message: 'Invitation already sent to the user',
    type: 'UleecoClientError',
    module: 'OCCUPANT',
  },
  160010: {
    responseCode: '160010',
    text: 'OCCUPANT_NOT_FOUND',
    statusCode: 404,
    http_status_text: 'NOT_FOUND',
    message: 'Occupant not found',
    type: 'UleecoClientError',
    module: 'OCCUPANT',
  },
  160012: {
    responseCode: '160012',
    text: 'OCCUPANT_INVITE_ID_NOT_FOUND',
    statusCode: 404,
    http_status_text: 'NOT_FOUND',
    message: 'Occupant_invite_id not found',
    type: 'UleecoClientError',
    module: 'OCCUPANT',
  },
  160013: {
    responseCode: '160013',
    text: 'INVITATION_ALREADY_ACCEPTED',
    statusCode: 422,
    http_status_text: 'UNPROCESSABLE_ENTITY',
    message: 'Invitation already accpeted',
    type: 'UleecoClientError',
    module: 'OCCUPANT',
  },
  160014: {
    responseCode: '160014',
    text: 'MAXIMUM_LIMIT_OF_10_OCCUPANTS_EXCEEDED',
    statusCode: 422,
    http_status_text: 'UNPROCESSABLE_ENTITY',
    message: 'Maximum limit of 10 Occupants exceeded',
    type: 'UleecoClientError',
    module: 'OCCUPANT',
  },
  160015: {
    responseCode: '160015',
    text: 'USER_DOES_NOT_HAVE_PERMISSION',
    statusCode: 403,
    http_status_text: 'FORBIDDEN',
    message: 'User does not have permission',
    type: 'UleecoClientError',
    module: 'OCCUPANT',
  },
  160018: {
    responseCode: '160018',
    text: 'DEVICE_ALERTS_NOT_FOUND',
    statusCode: 404,
    http_status_text: 'NOT_FOUND',
    message: 'Device alerts not found',
    type: 'UleecoClientError',
    module: 'OCCUPANT',
  },
  160019: {
    responseCode: '160019',
    text: 'OCCUPANT_CHECKED_IN_TO_LOCATIONS',
    statusCode: 422,
    http_status_text: 'UNPROCESSABLE_ENTITY',
    message: 'Occupant is checked in to locations, please check out from all the locations and try again!',
    type: 'UleecoClientError',
    module: 'OCCUPANT',
  },
  160020: {
    responseCode: '160020',
    text: 'OCCUPANT_HAVING_THEIR_OWN_GATEWAY',
    statusCode: 422,
    http_status_text: 'UNPROCESSABLE_ENTITY',
    message: 'Occupant having their own gateway!',
    type: 'UleecoClientError',
    module: 'OCCUPANT',
  },
  160021: {
    responseCode: '160021',
    text: 'MAXIMUM_LIMIT_OF_100_FOR_OCCUPANT_RESEND_INVITATION_EXCEEDED',
    statusCode: 422,
    http_status_text: 'UNPROCESSABLE_ENTITY',
    message: 'Maximum Limit of 100 for Occupant Resend Invitation Exceeded',
    type: 'UleecoClientError',
    module: 'OCCUPANT',
  },
  160022: {
    responseCode: '160022',
    text: 'OCCUPANTS_NOTIFICATION_TOKENS_ID_NOT_FOUND',
    statusCode: 422,
    http_status_text: 'UNPROCESSABLE_ENTITY',
    message: 'Occupants Notification Tokens Id Not Found ',
    type: 'UleecoClientError',
    module: 'OCCUPANT',
  },
  160023: {
    responseCode: '160023',
    text: 'OCCUPANTS_NOTIFICATION_TOKENS_ID_NOT_DELETED',
    statusCode: 422,
    http_status_text: 'UNPROCESSABLE_ENTITY',
    message: 'Occupants Notification Tokens Id Not Deleted',
    type: 'UleecoClientError',
    module: 'OCCUPANT',
  },
  160024: {
    responseCode: '160024',
    text: 'OCCUPANTS_NOTIFICATION_TOKENS_NOT_FOUND',
    statusCode: 422,
    http_status_text: 'UNPROCESSABLE_ENTITY',
    message: 'Occupants Notification Tokens Not Found',
    type: 'UleecoClientError',
    module: 'OCCUPANT',
  },
  160025: {
    responseCode: '160025',
    text: 'OCCUPANTS_DASHBOARD_ATTRIBUTES_NOT_FOUND',
    statusCode: 422,
    http_status_text: 'UNPROCESSABLE_ENTITY',
    message: 'Occupants Dashboard Attributes Not Found',
    type: 'UleecoClientError',
    module: 'OCCUPANT',
  },
  160026: {
    responseCode: '160026',
    text: 'OCCUPANTS_PERMISSIONS_NOT_FOUND',
    statusCode: 422,
    http_status_text: 'UNPROCESSABLE_ENTITY',
    message: 'Occupants Permissions Not Found',
    type: 'UleecoClientError',
    module: 'OCCUPANT',
  },
  160027: {
    responseCode: '160027',
    text: 'OCCUPANTS_PERMISSIONS_ID_NOT_FOUND',
    statusCode: 422,
    http_status_text: 'UNPROCESSABLE_ENTITY',
    message: 'Occupants Permissions Id Not Found ',
    type: 'UleecoClientError',
    module: 'OCCUPANT',
  },
  160028: {
    responseCode: '160028',
    text: 'OCCUPANTS_PERMISSIONS_ID_NOT_DELETED',
    statusCode: 422,
    http_status_text: 'UNPROCESSABLE_ENTITY',
    message: 'Occupants Permissions Id Not Deleted',
    type: 'UleecoClientError',
    module: 'OCCUPANT',
  },
  160029: {
    responseCode: '160029',
    text: 'OCCUPANTS_GROUPS_NOT_FOUND',
    statusCode: 422,
    http_status_text: 'UNPROCESSABLE_ENTITY',
    message: 'Occupants group not found',
    type: 'UleecoClientError',
    module: 'OCCUPANT',
  },
  160030: {
    responseCode: '160030',
    text: 'OCCUPANT_GROUPS_ID_NOT_FOUND',
    statusCode: 422,
    http_status_text: 'UNPROCESSABLE_ENTITY',
    message: 'Occupants group id not found',
    type: 'UleecoClientError',
    module: 'OCCUPANT',
  },
  160031: {
    responseCode: '160031',
    text: 'OCCUPANT_GROUPS_NOT_ADDED',
    statusCode: 422,
    http_status_text: 'UNPROCESSABLE_ENTITY',
    message: 'Occupants group not added',
    type: 'UleecoServerError',
    module: 'OCCUPANT',
  },
  160032: {
    responseCode: '160032',
    text: 'OCCUPANT_GROUPS_NOT_UPDATED',
    statusCode: 422,
    http_status_text: 'UNPROCESSABLE_ENTITY',
    message: 'Occupants group not updated',
    type: 'UleecoServerError',
    module: 'OCCUPANT',
  },
  160033: {
    responseCode: '160033',
    text: 'OCCUPANT_GROUPS_NOT_DELETED',
    statusCode: 422,
    http_status_text: 'UNPROCESSABLE_ENTITY',
    message: 'Occupants group not deleted',
    type: 'UleecoServerError',
    module: 'OCCUPANT',
  },
  160034: {
    responseCode: '160034',
    text: 'OCCUPANTS_DASHBOARD_ATTRIBUTES_NOT_ADDED',
    statusCode: 422,
    http_status_text: 'UNPROCESSABLE_ENTITY',
    message: 'Occupants Dashboard Attributes Not Added',
    type: 'UleecoServerError',
    module: 'OCCUPANT',
  },
  160035: {
    responseCode: '160035',
    text: 'OCCUPANTS_NOTIFICATION_TOKENS_NOT_ADDED',
    statusCode: 422,
    http_status_text: 'UNPROCESSABLE_ENTITY',
    message: 'Occupants Notification Tokens Not Added',
    type: 'UleecoServerError',
    module: 'OCCUPANT',
  },
  160036: {
    responseCode: '160036',
    text: 'OCCUPANTS_PERMISSIONS_NOT_ADDED',
    statusCode: 422,
    http_status_text: 'UNPROCESSABLE_ENTITY',
    message: 'Occupants Permissions Not Added',
    type: 'UleecoServerError',
    module: 'OCCUPANT',
  },
  160037: {
    responseCode: '160037',
    text: 'OCCUPANTS_DASHBOARD_ATTRIBUTES_NOT_UPDATED',
    statusCode: 422,
    http_status_text: 'UNPROCESSABLE_ENTITY',
    message: 'Occupants Dashboard Attributes Not Updated',
    type: 'UleecoServerError',
    module: 'OCCUPANT',
  },
  160038: {
    responseCode: '160038',
    text: 'OCCUPANTS_NOTIFICATION_TOKENS_NOT_UPDATED',
    statusCode: 422,
    http_status_text: 'UNPROCESSABLE_ENTITY',
    message: 'Occupants Notification Tokens Not Updated',
    module: 'OCCUPANT',
  },
  160039: {
    responseCode: '160039',
    text: 'OCCUPANTS_PERMISSIONS_NOT_DELETED',
    statusCode: 422,
    http_status_text: 'UNPROCESSABLE_ENTITY',
    message: 'Occupants Permissions Not Deleted',
    type: 'UleecoServerError',
    module: 'OCCUPANT',
  },
  160040: {
    responseCode: '160040',
    text: 'OCCUPANTS_DASHBOARD_ATTRIBUTES_ID_NOT_FOUND',
    statusCode: 422,
    http_status_text: 'UNPROCESSABLE_ENTITY',
    message: 'Occupants Dashboard attribute Id Not Found ',
    type: 'UleecoClientError',
    module: 'OCCUPANT',
  },
  160041: {
    responseCode: '160041',
    text: 'OCCUPANTS_DASHBOARD_ATTRIBUTES_ID_NOT_DELETED',
    statusCode: 422,
    http_status_text: 'UNPROCESSABLE_ENTITY',
    message: 'Occupants Dashboard attribute Id Not Deleted',
    type: 'UleecoServerError',
    module: 'OCCUPANT',
  },
  160043: {
    responseCode: '160043',
    text: 'ERROR_WHILE_GETTING_OCCUPANT_PROFILE',
    statusCode: 422,
    http_status_text: 'UNPROCESSABLE_ENTITY',
    message: 'Error while getting occupant profile',
    type: 'UleecoServerError',
    module: 'OCCUPANT',
  },
  160044: {
    responseCode: '160044',
    text: 'OCCUPANTS_PERMISSIONS_ALREADY_EXIST',
    statusCode: 422,
    http_status_text: 'UNPROCESSABLE_ENTITY',
    message: 'The Email Address has already been taken',
    type: 'UleecoClientError',
    module: 'OCCUPANT',
  },
  160045: {
    responseCode: '160045',
    text: 'PERMISSION_DENIED',
    statusCode: 422,
    http_status_text: 'UNPROCESSAB,E_ENTITY',
    message: 'Permission denied',
    type: 'UleecoClientError',
    module: 'OCCUPANT',
  },
  160046: {
    responseCode: '160046',
    text: 'OCCUPANTS_PERMISSIONS_NOT_FOUND',
    statusCode: 422,
    http_status_text: 'UNPROCESSABLE_ENTITY',
    message: 'Occupants Permissions Not Found',
    type: 'UleecoClientError',
    module: 'OCCUPANT',
  },
  160047: {
    responseCode: '160047',
    text: 'OCCUPANT_ALREADY_EXISTS',
    statusCode: 400,
    http_status_text: 'UNPROCESSABLE_ENTITY',
    message: 'Occupant already exists',
    type: 'UleecoClientError',
    module: 'OCCUPANT',
  },
  160048: {
    responseCode: '160048',
    text: 'OCCUPANT_IS_NOT_CONFIRMED',
    statusCode: 401,
    http_status_text: 'NOT_AUTHORIZED',
    message: 'Occupant is not confirmed',
    type: 'UleecoClientError',
    module: 'OCCUPANT',
  },
  160049: {
    responseCode: '160049',
    text: 'INVALID_VERIFICATION_CODE',
    statusCode: 422,
    http_status_text: 'NOT_AUTHORIZED',
    message: 'Invalid verification code provided, please try again',
    type: 'UleecoClientError',
    module: 'OCCUPANT',
  },
  160050: {
    responseCode: '160050',
    text: 'OCCUPANTS_LOCATIONS_ID_NOT_FOUND',
    statusCode: 422,
    http_status_text: 'UNPROCESSABLE_ENTITY',
    message: 'Occupants locations id not found',
    type: 'UleecoClientError',
    module: 'OCCUPANT',
  },
  160051: {
    responseCode: '160051',
    text: 'OCCUPANT_NOT_REGISTERED',
    statusCode: 422,
    http_status_text: 'UNPROCESSABLE_ENTITY',
    message: 'Occupant not registered',
    type: 'UleecoClientError',
    module: 'OCCUPANT',
  },
  160052: {
    responseCode: '160052',
    text: 'ADMIN_USER_CANNOT_BE_DELETED',
    statusCode: 422,
    http_status_text: 'UNPROCESSABLE_ENTITY',
    message: 'Admin user can not be deleted, pass x-source in headers if missing.',
    type: 'UleecoClientError',
    module: 'USER',
  },
  160053: {
    responseCode: '160053',
    text: 'DEVICE_ID_VALIDATION',
    statusCode: 422,
    http_status_text: 'UNPROCESSABLE_ENTITY',
    message: 'Invalid devices array',
    type: 'UleecoClientError',
    module: 'GROUPS',
  },
  160054: {
    responseCode: '160054',
    text: 'OCCUPANTS_PERMISSIONS_METADATA_NOT_ADDED',
    statusCode: 422,
    http_status_text: 'UNPROCESSABLE_ENTITY',
    message: 'Occupants permissions metadata not added',
    type: 'UleecoServerError',
    module: 'OCCUPANT',
  },
  160055: {
    responseCode: '160055',
    text: 'OCCUPANTS_PERMISSIONS_METADATA_NOT_FOUND',
    statusCode: 422,
    http_status_text: 'UNPROCESSABLE_ENTITY',
    message: 'Occupants permissions metadata not found',
    type: 'UleecoClientError',
    module: 'OCCUPANT',
  },
  160056: {
    responseCode: '160056',
    text: 'OCCUPANTS_PERMISSIONS_METADATA_NOT_FOUND',
    statusCode: 422,
    http_status_text: 'UNPROCESSABLE_ENTITY',
    message: 'Error while getting occupants permissions metadata ',
    type: 'UleecoServerError',
    module: 'OCCUPANT',
  },
  160057: {
    responseCode: '160057',
    text: 'OCCUPANTS_PERMISSIONS_METADATA_NOT_UPDATED',
    statusCode: 422,
    http_status_text: 'UNPROCESSABLE_ENTITY',
    message: 'Occupants permissions metadata not updated',
    type: 'UleecoServerError',
    module: 'OCCUPANT',
  },
  160058: {
    responseCode: '160058',
    text: 'OCCUPANTS_PERMISSIONS_METADATA_NOT_DELETED',
    statusCode: 422,
    http_status_text: 'UNPROCESSABLE_ENTITY',
    message: 'Occupants permissions metadata not deleted',
    type: 'UleecoServerError',
    module: 'OCCUPANT',
  },
  160059: {
    responseCode: '160059',
    text: 'PEMISSION_DENIED',
    statusCode: 422,
    http_status_text: 'UNPROCESSABLE_ENTITY',
    message: 'Only owner can update the auto_switch_status',
    type: 'UleecoClientError',
    module: 'OCCUPANT',
  },
  160060: {
    responseCode: '160060',
    text: 'PEMISSION_DENIED',
    statusCode: 422,
    http_status_text: 'UNPROCESSABLE_ENTITY',
    message: 'Occupant cannot delete own geofencing data',
    type: 'UleecoClientError',
    module: 'OCCUPANT',
  },
  160061: {
    responseCode: '160061',
    text: 'NOT_FOUND',
    statusCode: 422,
    http_status_text: 'UNPROCESSABLE_ENTITY',
    message: 'Occupant_permissions_id not found to delete',
    type: 'UleecoClientError',
    module: 'OCCUPANT',
  },
  160062: {
    responseCode: '160062',
    text: 'NAME_MUST_BE_UNIQUE',
    statusCode: 422,
    http_status_text: 'UNPROCESSABLE_ENTITY',
    message: 'You must use unique name',
    type: 'UleecoClientError',
    module: 'OCCUPANT',
  },
  160063: {
    responseCode: '160063',
    text: 'OCCUPANTS_EQUIPMENT_DATA_NOT_ADDED',
    statusCode: 422,
    http_status_text: 'UNPROCESSABLE_ENTITY',
    message: 'Occupants equipment data not added',
    type: 'UleecoServerError',
    module: 'OCCUPANT',
  },
  160064: {
    responseCode: '160064',
    text: 'OCCUPANTS_EQUIPMENT_DATA_NOT_UPDATED',
    statusCode: 422,
    http_status_text: 'UNPROCESSABLE_ENTITY',
    message: 'Occupants equipment data not updated',
    type: 'UleecoServerError',
    module: 'OCCUPANT',
  },
  160065: {
    responseCode: '160065',
    text: 'OCCUPANTS_EQUIPMENT_DATA_NOT_DELETED',
    statusCode: 422,
    http_status_text: 'UNPROCESSABLE_ENTITY',
    message: 'Occupants equipment data not deleted',
    type: 'UleecoServerError',
    module: 'OCCUPANT',
  },
  160066: {
    responseCode: '160066',
    text: 'OCCUPANTS_EQUIPMENT_DATA_NOT_FOUND',
    statusCode: 422,
    http_status_text: 'UNPROCESSABLE_ENTITY',
    message: 'Occupants equipment data not found',
    type: 'UleecoServerError',
    module: 'OCCUPANT',
  },
  160067: {
    responseCode: '160067',
    text: 'OCCUPANTS_DASHBOARD_ATTRIBUTES_TYPE_NOT_EXISTS',
    statusCode: 422,
    http_status_text: 'UNPROCESSABLE_ENTITY',
    message: 'Occupants Dashboard Attributes Type Not Exists',
    type: 'UleecoClientError',
    module: 'OCCUPANT',
  },
  160068: {
    responseCode: '160068',
    text: 'ERROR_WHIE_GETTING_THE EQUIPMENT_DATA',
    statusCode: 422,
    http_status_text: 'UNPROCESSABLE_ENTITY',
    message: 'Error while getting the equipment data',
    type: 'UleecoClientError',
    module: 'OCCUPANT',
  },
  170001: {
    responseCode: '170001',
    text: 'DATABASE_ERROR',
    statusCode: 503,
    http_status_text: 'Gateway_Timeout',
    message: 'Database server connection error.',
    type: 'UleecoServerError',
    module: 'STATUS',
  },
  170002: {
    responseCode: '170002',
    text: 'DATABASE_ERROR',
    statusCode: 503,
    http_status_text: 'DB_ERROR_IN_PREFERENCES',
    message: 'Error getting dt preferences.',
    type: 'UleecoServerError',
    module: 'STATUS',
  },
  170003: {
    responseCode: '170003',
    text: 'DATABASE_ERROR',
    statusCode: 503,
    http_status_text: 'DB_ERROR_IN_PREFERENCES',
    message: 'Error creating dt preferences.',
    type: 'UleecoServerError',
    module: 'STATUS',
  },
  170004: {
    responseCode: '170004',
    text: 'ACCESS_DENIED',
    statusCode: 403,
    http_status_text: 'ACCESS_DENIED_FOR_PARENT_DEVICES',
    message: 'Access denies to get parent devices',
    type: 'UleecoClientError',
    module: 'Devices',
  },
  170005: {
    responseCode: '170005',
    text: 'LOCATION_WITH_SAME_NAME_EXISTS',
    statusCode: 409,
    http_status_text: 'LOCATION_WITH_SAME_NAME_EXISTS',
    message: 'Location with same name already exists',
    type: 'UleecoClientError',
    module: 'Locations',
  },
  170006: {
    responseCode: '170006',
    text: 'CAN_NO_DELETE_LOCATION',
    statusCode: 422,
    http_status_text: 'UNPROCESSABLE_ENTITY',
    message: 'Can not delete location as occupants are checked in or invited to this location',
    type: 'UleecoClientError',
    module: 'Locations',
  },
  280000: {
    responseCode: '280000',
    text: 'DEVICE_HISTORY_ERROR',
    statusCode: 422,
    http_status_text: 'DEVICE_HISTORY_ERROR',
    message: 'Error in device history',
    type: 'UleecoServerError',
    module: 'DEVICES',
  },
  290000: {
    responseCode: '290000',
    text: 'DEVICE_USER_ANALYTICS_ERROR',
    statusCode: 422,
    http_status_text: 'DEVICE_USER_ANALYTICS_ERROR',
    message: 'Error in device user_analytics',
    type: 'UleecoServerError',
    module: 'DEVICES',
  },
  320001: {
    responseCode: '320001',
    text: 'USER_PREFERENCES_NOT_ADDED',
    statusCode: 422,
    http_status_text: 'UNPROCESSABLE_ENTITY',
    message: 'User preferences not added',
    type: 'UleecoServerError',
    module: 'USER_PREFERENCES',
  },
  320002: {
    responseCode: '320002',
    text: 'USER_PREFERENCES_FOR_THE USER_ARE_ALREADY_ADDED',
    statusCode: 422,
    http_status_text: 'UNPROCESSABLE_ENTITY',
    message: 'User preferences for the user are already added',
    type: 'UleecoServerError',
    module: 'USER_PREFERENCES',
  },
  320003: {
    responseCode: '320003',
    text: 'USER_PREFERENCES_NOT_FOUND',
    statusCode: 404,
    http_status_text: 'NOT_FOUND',
    message: 'User preferences not found',
    type: 'UleecoClientError',
    module: 'USER_PREFERENCES',
  },
  320004: {
    responseCode: '320004',
    text: 'USER_PREFERENCES_NOT_UPDATED',
    statusCode: 422,
    http_status_text: 'UNPROCESSABLE_ENTITY',
    message: 'User preferences not updated',
    type: 'UleecoServerError',
    module: 'USER_PREFERENCES',
  },
  320005: {
    responseCode: '320005',
    text: 'UN_AUTHORIZED',
    statusCode: 401,
    http_status_text: 'NOT_AUTHORIZED',
    message: 'Not Authorized to perform this action',
    type: 'UleecoClientError',
    module: 'USERS',
  },
  330000: {
    responseCode: '330000',
    text: 'ONETOUCH_RULE_NOT_ADDED',
    statusCode: 422,
    http_status_text: 'UNPROCESSABLE_ENTITY',
    message: 'Onetouch rules not added',
    type: 'UleecoServerError',
    module: 'ONETOUCH_RULES',
  },
  330001: {
    responseCode: '330001',
    text: 'ONETOUCH_RULE_NOT_UPDATED',
    statusCode: 422,
    http_status_text: 'UNPROCESSABLE_ENTITY',
    message: 'Onetouch rules not updated',
    type: 'UleecoServerError',
    module: 'ONETOUCH_RULES',
  },
  330002: {
    responseCode: '330002',
    text: 'ONETOUCH_RULE_GET',
    statusCode: 422,
    http_status_text: 'UNPROCESSABLE_ENTITY',
    message: 'Onetouch rule not found',
    type: 'UleecoClientError',
    module: 'ONETOUCH_RULES',
  },
  330003: {
    responseCode: '330003',
    text: 'ONETOUCH_RULES_GET',
    statusCode: 422,
    http_status_text: 'UNPROCESSABLE_ENTITY',
    message: 'Onetouch rules not found',
    type: 'UleecoClientError',
    module: 'ONETOUCH_RULES',
  },
  330004: {
    responseCode: '330004',
    text: 'ONETOUCH_RULE_NOT_DELETED',
    statusCode: 422,
    http_status_text: 'UNPROCESSABLE_ENTITY',
    message: 'Onetouch rules not deleted',
    type: 'UleecoServerError',
    module: 'ONETOUCH_RULES',
  },
  330005: {
    responseCode: '330005',
    text: 'GATEWAY_SHADOW_NOT_UPDATED',
    statusCode: 422,
    http_status_text: 'UNPROCESSABLE_ENTITY',
    message: 'Gateway shadow not updated',
    type: 'UleecoServerError',
    module: 'ONETOUCH_RULES',
  },
  330006: {
    responseCode: '330006',
    text: 'ONE_TOUCH_COMMUNICATION_CONFIG_NOT_FOUND',
    statusCode: 422,
    http_status_text: 'UNPROCESSABLE_ENTITY',
    message: 'One Touch Communication Config Not Found',
    type: 'UleecoClientError',
    module: 'ONE_TOUCH_COMMUNICATION_CONFIG',
  },
  330007: {
    responseCode: '330007',
    text: 'ONE_TOUCH_COMMUNICATION_CONFIG_NOT_UPDATED',
    statusCode: 422,
    http_status_text: 'UNPROCESSABLE_ENTITY',
    message: 'One Touch Communication Config Not Updated',
    type: 'UleecoServerError',
    module: 'ONE_TOUCH_COMMUNICATION_CONFIG',
  },
  330008: {
    responseCode: '330008',
    text: 'ONE_TOUCH_COMMUNICATION_CONFIG_NOT_DELETED',
    statusCode: 422,
    http_status_text: 'UNPROCESSABLE_ENTITY',
    message: 'One Touch Communication Config Not Deleted',
    type: 'UleecoServerError',
    module: 'ONE_TOUCH_COMMUNICATION_CONFIG',
  },
  330009: {
    responseCode: '330009',
    text: 'ONE_TOUCH_COMMUNICATION_CONFIG_NOT_ADDED',
    statusCode: 422,
    http_status_text: 'UNPROCESSABLE_ENTITY',
    message: 'One Touch Communication Config Not Added',
    type: 'UleecoServerError',
    module: 'ONE_TOUCH_COMMUNICATION_CONFIG',
  },
  330010: {
    responseCode: '330010',
    text: 'ONE_TOUCH_COMMUNICATION_CONFIG_ACTION_TRIGGER_KEY_NOT_FOUND',
    statusCode: 422,
    http_status_text: 'UNPROCESSABLE_ENTITY',
    message: 'One Touch Communication Config Action Trigger Key Not Found',
    type: 'UleecoClientError',
    module: 'ONE_TOUCH_COMMUNICATION_CONFIG',
  },
  330011: {
    responseCode: '330011',
    text: 'ONE_TOUCH_COMMUNICATION_CONFIG_ONE_TOUCH_RULE_ID_NOT_FOUND',
    statusCode: 422,
    http_status_text: 'UNPROCESSABLE_ENTITY',
    message: 'One Touch Communication Config Rule Id Not Found',
    type: 'UleecoClientError',
    module: 'ONE_TOUCH_COMMUNICATION_CONFIG',
  },
  330012: {
    responseCode: '330012',
    text: 'ONE_TOUCH_COMMUNICATION_CONFIGS_NOT_DELETED',
    statusCode: 422,
    http_status_text: 'UNPROCESSABLE_ENTITY',
    message: 'One Touch Communication Configs Not Deleted',
    type: 'UleecoServerError',
    module: 'ONE_TOUCH_COMMUNICATION_CONFIG',
  },
  330013: {
    responseCode: '330013',
    text: 'ONE_TOUCH_RULES_RECORD_ALREADY_EXIST',
    statusCode: 422,
    http_status_text: 'UNPROCESSABLE_ENTITY',
    message: 'One Touch Rules key / rule_trigger_key Already Exist',
    type: 'UleecoClientError',
    module: 'ONETOUCH_RULES',
  },
  330014: {
    responseCode: '330014',
    text: 'ONE_TOUCH_COMMUNICATION_CONFIGS_RECORD_ALREADY_EXIST',
    statusCode: 422,
    http_status_text: 'UNPROCESSABLE_ENTITY',
    message: 'One Touch Communication configs action_trigger_key Already Exist',
    type: 'UleecoClientError',
    module: 'ONE_TOUCH_COMMUNICATION_CONFIG',
  },
  330015: {
    responseCode: '330015',
    text: 'ONETOUCH_RULE',
    statusCode: 422,
    http_status_text: 'UNPROCESSABLE_ENTITY',
    message: 'RuleTriggerKey Not Found',
    type: 'UleecoClientError',
    module: 'ONE_TOUCH_RULES',
  },
  330016: {
    responseCode: '330015',
    text: 'ONETOUCH_RULES_GET',
    statusCode: 422,
    http_status_text: 'UNPROCESSABLE_ENTITY',
    message: 'Error while getting onetouch rules.',
    type: 'UleecoServerError',
    module: 'ONE_TOUCH_RULES',
  },
  330017: {
    responseCode: '330017',
    text: 'ONETOUCH_CB_CONFIG_GET',
    statusCode: 422,
    http_status_text: 'UNPROCESSABLE_ENTITY',
    message: 'Error while getting onetouch cb configs.',
    type: 'UleecoServerError',
    module: 'ONE_TOUCH_RULES',
  },
  330018: {
    responseCode: '330018',
    text: 'ONETOUCH_CB_CONFIG',
    statusCode: 422,
    http_status_text: 'UNPROCESSABLE_ENTITY',
    message: 'Array id already exist for the gateway',
    type: 'UleecoServerError',
    module: 'ONE_TOUCH_RULES',
  },
  330019: {
    responseCode: '330019',
    text: 'ONETOUCH_CB_CONFIG_CREATE',
    statusCode: 422,
    http_status_text: 'UNPROCESSABLE_ENTITY',
    message: 'Error while adding onetouch cb configs.',
    type: 'UleecoServerError',
    module: 'ONE_TOUCH_RULES',
  },
  330020: {
    responseCode: '330020',
    text: 'ONETOUCH_CB_CONFIG',
    statusCode: 422,
    http_status_text: 'UNPROCESSABLE_ENTITY',
    message: 'Array id limit 128 exceeded for the gateway',
    type: 'UleecoServerError',
    module: 'ONE_TOUCH_RULES',
  },
  340000: {
    responseCode: '340000',
    text: 'OCCUPANT_DASHBOARD_ERROR',
    statusCode: 422,
    http_status_text: 'UNPROCESSABLE_ENTITY',
    message: 'occupant dashboard service error',
    type: 'UleecoServerError',
    module: 'OCCUPANT_DASHBOARD_SERVICE',
  },
  340001: {
    responseCode: '340001',
    text: 'OCCUPANT_HOME_ERROR',
    statusCode: 422,
    http_status_text: 'UNPROCESSABLE_ENTITY',
    message: 'occupant home error',
    type: 'UleecoServerError',
    module: 'OCCUPANT_HOME_SERVICE',
  },
  350000: {
    responseCode: '350000',
    text: 'PREDEFINED_RULE_ALREADY_EXISTS',
    statusCode: 422,
    http_status_text: 'UNPROCESSABLE_ENTITY',
    message: 'PreDefined Rule Already Exists',
    type: 'UleecoServerError',
    module: 'PREDEFINED_RULES',
  },
  350001: {
    responseCode: '350001',
    text: 'PREDEFINED_RULE_NOT_UPDATED',
    statusCode: 422,
    http_status_text: 'UNPROCESSABLE_ENTITY',
    message: 'PreDefined Rules Not Updated',
    type: 'UleecoServerError',
    module: 'PREDEFINED_RULES',
  },
  350002: {
    responseCode: '350002',
    text: 'PREDEFINED_RULE_GET',
    statusCode: 422,
    http_status_text: 'UNPROCESSABLE_ENTITY',
    message: 'PreDefined Rules Not Found',
    type: 'UleecoClientError',
    module: 'PREDEFINED_RULES',
  },
  350003: {
    responseCode: '350003',
    text: 'PREDEFINED_RULES_GET',
    statusCode: 422,
    http_status_text: 'UNPROCESSABLE_ENTITY',
    message: 'PreDefined Rules Not Found',
    type: 'UleecoClientError',
    module: 'PREDEFINED_RULES',
  },
  350004: {
    responseCode: '350004',
    text: 'PREDEFINED_RULE_NOT_DELETED',
    statusCode: 422,
    http_status_text: 'UNPROCESSABLE_ENTITY',
    message: 'PreDefined Rules Not Deleted',
    type: 'UleecoServerError',
    module: 'PREDEFINED_RULES',
  },
  350005: {
    responseCode: '350005',
    text: 'GATEWAY_SHADOW_NOT_UPDATED',
    statusCode: 422,
    http_status_text: 'UNPROCESSABLE_ENTITY',
    message: 'Gateway shadow not updated',
    type: 'UleecoServerError',
    module: 'PREDEFINED_RULES',
  },
  350006: {
    responseCode: '350006',
    text: 'DEVICE_NOT_FOUND',
    statusCode: 422,
    http_status_text: 'UNPROCESSABLE_ENTITY',
    message: 'Device not attached to gateway',
    type: 'UleecoClientError',
    module: 'PREDEFINED_RULES',
  },
  350007: {
    responseCode: '350003',
    text: 'PREDEFINED_RULES_GET',
    statusCode: 422,
    http_status_text: 'UNPROCESSABLE_ENTITY',
    message: 'Error while getting pre defined rules.',
    type: 'UleecoServerError',
    module: 'PREDEFINED_RULES',
  },
  360001: {
    responseCode: '360001',
    text: 'ALERT_COMMUNICATION_CONFIGS_NOT_ADDED',
    statusCode: 422,
    http_status_text: 'UNPROCESSABLE_ENTITY',
    message: 'Alert communication configs not added',
    type: 'UleecoServerError',
    module: 'ALERT_COMMUNICATION_CONFIGS',
  },
  360002: {
    responseCode: '360002',
    text: 'ALERT_COMMUNICATION_CONFIGS_NOT_UPDATED',
    statusCode: 422,
    http_status_text: 'UNPROCESSABLE_ENTITY',
    message: 'Alert communication configs not updated',
    type: 'UleecoServerError',
    module: 'ALERT_COMMUNICATION_CONFIGS',
  },
  360003: {
    responseCode: '360003',
    text: 'ALERT_COMMUNICATION_CONFIGS_NOT_FOUND',
    statusCode: 404,
    http_status_text: 'UNPROCESSABLE_ENTITY',
    message: 'Alert communication configs not found',
    type: 'UleecoClientError',
    module: 'ALERT_COMMUNICATION_CONFIGS',
  },

  370001: {
    responseCode: '370001',
    text: 'RULE_GROUPS_NOT_FOUND',
    statusCode: 422,
    http_status_text: 'UNPROCESSABLE_ENTITY',
    message: 'Rule Group Not found',
    type: 'UleecoClientError',
    module: 'RULEGROUPS',
  },
  370002: {
    responseCode: '370002',
    text: 'RULE_GROUPS_ID_NOT_FOUND',
    statusCode: 422,
    http_status_text: 'UNPROCESSABLE_ENTITY',
    message: 'Rule Group ID Not found',
    type: 'UleecoClientError',
    module: 'RULEGROUPS',
  },
  370003: {
    responseCode: '370003',
    text: 'RULE_GROUPS_NOT_ADDED',
    statusCode: 422,
    http_status_text: 'UNPROCESSABLE_ENTITY',
    message: 'Rule Group Not Added',
    type: 'UleecoServerError',
    module: 'RULEGROUPS',
  },
  370004: {
    responseCode: '370004',
    text: 'RULE_GROUPS_NOT_UPDATED',
    statusCode: 422,
    http_status_text: 'UNPROCESSABLE_ENTITY',
    message: 'Rule Group Not Updated',
    type: 'UleecoServerError',
    module: 'RULEGROUPS',
  },
  370005: {
    responseCode: '370005',
    text: 'RULE_GROUPS_NOT_DELETED',
    statusCode: 422,
    http_status_text: 'UNPROCESSABLE_ENTITY',
    message: 'Rule Group Not Deleted',
    type: 'UleecoServerError',
    module: 'RULEGROUPS',
  },
  370006: {
    responseCode: '370006',
    text: 'RULE_GROUP_ENABLE_ERROR',
    statusCode: 422,
    http_status_text: 'UNPROCESSABLE_ENTITY',
    message: 'Rule Group Enable Error',
    type: 'UleecoServerError',
    module: 'RULEGROUPS',
  },
  370007: {
    responseCode: '370007',
    text: 'RULE_GROUP_DISABLE_ERROR',
    statusCode: 422,
    http_status_text: 'UNPROCESSABLE_ENTITY',
    message: 'Rule Group Disable Error',
    type: 'UleecoServerError',
    module: 'RULEGROUPS',
  },
  370008: {
    responseCode: '370008',
    text: 'RULE_GROUP_NAME_ALREADY_EXIST',
    statusCode: 422,
    http_status_text: 'UNPROCESSABLE_ENTITY',
    message: 'Rule Group name already exist',
    type: 'UleecoClientError',
    module: 'RULEGROUPS',
  },
  370009: {
    responseCode: '370009',
    text: 'DEFAULT_MY_STATUS_CANNOT_BE_DELETED',
    statusCode: 422,
    http_status_text: 'UNPROCESSABLE_ENTITY',
    message: 'Defult my status Home or Away cannot be deleted',
    type: 'UleecoClientError',
    module: 'RULEGROUPS',
  },
  380001: {
    responseCode: '380001',
    text: 'DEVICE_PROVISION',
    statusCode: 422,
    http_status_text: 'UNPROCESSABLE_ENTITY',
    message: 'Device provision api failed',
    type: 'UleecoClientError',
    module: 'DEVICE_PROVISION',
  },
  390001: {
    responseCode: '390001',
    text: 'DEVICE_ALERTS_NOT_FOUND',
    statusCode: 404,
    http_status_text: 'NOT_FOUND',
    message: 'Device alert not found',
    type: 'UleecoClientError',
    module: 'DEVICE_ALERTS',
  },
  390002: {
    responseCode: '390002',
    text: 'DEVICE_ALERTS_UPDATE_ERROR',
    statusCode: 404,
    http_status_text: 'NOT_FOUND',
    message: 'Device alert update error',
    type: 'UleecoServerError',
    module: 'DEVICE_ALERTS',
  },
  410001: {
    responseCode: '410001',
    text: 'SCHEDULES_NOT_FOUND',
    statusCode: 422,
    http_status_text: 'UNPROCESSABLE_ENTITY',
    message: 'Schedules Not found',
    type: 'UleecoClientError',
    module: 'SCHEDULES',
  },
  410002: {
    responseCode: '410002',
    text: 'SCHEDULES_ID_NOT_FOUND',
    statusCode: 422,
    http_status_text: 'UNPROCESSABLE_ENTITY',
    message: 'Schedules ID Not found',
    type: 'UleecoClientError',
    module: 'SCHEDULES',
  },
  410003: {
    responseCode: '410003',
    text: 'SCHEDULES_NOT_ADDED',
    statusCode: 422,
    http_status_text: 'UNPROCESSABLE_ENTITY',
    message: 'Schedules Not Added',
    type: 'UleecoServerError',
    module: 'SCHEDULES',
  },
  410004: {
    responseCode: '410004',
    text: 'SCHEDULES_NOT_UPDATED',
    statusCode: 422,
    http_status_text: 'UNPROCESSABLE_ENTITY',
    message: 'Schedules Not Updated',
    type: 'UleecoServerError',
    module: 'SCHEDULES',
  },
  410005: {
    responseCode: '410005',
    text: 'SCHEDULES_NOT_DELETED',
    statusCode: 422,
    http_status_text: 'UNPROCESSABLE_ENTITY',
    message: 'Schedules Not Deleted',
    type: 'UleecoServerError',
    module: 'SCHEDULES',
  },
  410006: {
    responseCode: '410006',
    text: 'DEVICE_SHADOW_NOT_UPDATED',
    statusCode: 422,
    http_status_text: 'UNPROCESSABLE_ENTITY',
    message: 'Device Shadow Not Updated',
    type: 'UleecoServerError',
    module: 'SCHEDULES',
  },
  410007: {
    responseCode: '410007',
    text: 'SCHEDULES_GET',
    statusCode: 422,
    http_status_text: 'UNPROCESSABLE_ENTITY',
    message: 'Schedules Not Found',
    type: 'UleecoClientError',
    module: 'SCHEDULES',
  },
  410008: {
    responseCode: '410008',
    text: 'GATEWAY_OFFLINE',
    statusCode: 422,
    http_status_text: 'UNPROCESSABLE_ENTITY',
    message: 'Gateway is Offline',
    type: 'UleecoClientError',
    module: 'DEVICES',
  },
  410009: {
    responseCode: '410009',
    text: 'SCHEDULES_ACTIONS_MAX_LIMIT_20_EXCEEDED',
    statusCode: 422,
    http_status_text: 'UNPROCESSABLE_ENTITY',
    message: 'Schedules Actions Max Limit 20 Exceeded',
    type: 'UleecoClientError',
    module: 'SCHEDULES',
  },
  410010: {
    responseCode: '410010',
    text: 'DEVCE_ID_SCHEDULES_MAX_LIMIT_200_EXCEEDED',
    statusCode: 422,
    http_status_text: 'UNPROCESSABLE_ENTITY',
    message: 'Device Ids Schedules Max Limit 200 Exceeded',
    type: 'UleecoClientError',
    module: 'SCHEDULES',
  },
  410011: {
    responseCode: '410011',
    text: 'MAX_LIMIT_OF_2MB_EXCEEDED_FOR_DEVICE_SCHEDULE',
    statusCode: 422,
    http_status_text: 'UNPROCESSABLE_ENTITY',
    message: 'Max Limit of 2mb Exceeded for Device Schedule',
    type: 'UleecoClientError',
    module: 'SCHEDULES',
  },
  410012: {
    responseCode: '410012',
    text: 'MAX_LIMIT_OF_3MB_EXCEEDED_FOR_DEVICE_SCHEDULE',
    statusCode: 422,
    http_status_text: 'UNPROCESSABLE_ENTITY',
    message: 'Max Limit of 3mb Exceeded for Device Schedule',
    type: 'UleecoClientError',
    module: 'SCHEDULES',
  },
  410013: {
    responseCode: '410013',
    text: 'MAX_LIMIT_OF_5MB_EXCEEDED_FOR_DEFAULT_DEVICE_SCHEDULE',
    statusCode: 422,
    http_status_text: 'UNPROCESSABLE_ENTITY',
    message: 'Max Limit of 5mb Exceeded for Default Device Schedule',
    type: 'UleecoClientError',
    module: 'SCHEDULES',
  },
  410014: {
    responseCode: '410014',
    text: 'SCHEDULES_DEVICE_ID_NOT_FOUND',
    statusCode: 422,
    http_status_text: 'UNPROCESSABLE_ENTITY',
    message: 'Schedules Device ID Not found',
    type: 'UleecoClientError',
    module: 'SCHEDULES',
  },
  410015: {
    responseCode: '410015',
    text: 'SINGLE_CONTROL_GET_ERROR',
    statusCode: 422,
    http_status_text: 'UNPROCESSABLE_ENTITY',
    message: 'Error while getting the single controls',
    type: 'UleecoServerError',
    module: 'SINGLE_CONTROLS',
  },
  410016: {
    responseCode: '410016',
    text: 'MAC_ADDRESS_NOT_FOUND',
    statusCode: 422,
    http_status_text: 'UNPROCESSABLE_ENTITY',
    message: 'Device mac_address not found',
    type: 'UleecoServerError',
    module: 'SCHEDULES',
  },
  420001: {
    responseCode: '420001',
    text: 'SINGLE_CONTROL_ADD_ERROR',
    statusCode: 422,
    http_status_text: 'UNPROCESSABLE_ENTITY',
    message: 'Error while adding the single control',
    type: 'UleecoServerError',
    module: 'SINGLE_CONTROLS',
  },
  420002: {
    responseCode: '420002',
    text: 'SINGLE_CONTROL_NOT_FOUND',
    statusCode: 404,
    http_status_text: 'UNPROCESSABLE_ENTITY',
    message: 'Not found the single control',
    type: 'UleecoClientError',
    module: 'SINGLE_CONTROLS',
  },
  420003: {
    responseCode: '420003',
    text: 'SINGLE_CONTROL_DEVICE_ADD_ERROR',
    statusCode: 422,
    http_status_text: 'UNPROCESSABLE_ENTITY',
    message: 'Error while adding the single control device',
    type: 'UleecoServerError',
    module: 'SINGLE_CONTROLS',
  },
  420004: {
    responseCode: '420004',
    text: 'SINGLE_CONTROL_DEVICE_GET_ERROR',
    statusCode: 422,
    http_status_text: 'UNPROCESSABLE_ENTITY',
    message: 'Error while getting the single control device',
    type: 'UleecoServerError',
    module: 'SINGLE_CONTROLS',
  },
  420005: {
    responseCode: '420005',
    text: 'SINGLE_CONTROL_UPDATE_ERROR',
    statusCode: 422,
    http_status_text: 'UNPROCESSABLE_ENTITY',
    message: 'Error while updating the single control',
    type: 'UleecoServerError',
    module: 'SINGLE_CONTROLS',
  },
  420006: {
    responseCode: '420006',
    text: 'SINGLE_CONTROL_DEVICE_DELETE_ERROR',
    statusCode: 422,
    http_status_text: 'UNPROCESSABLE_ENTITY',
    message: 'Error while deleting the single control device',
    type: 'UleecoServerError',
    module: 'SINGLE_CONTROLS',
  },
  420007: {
    responseCode: '420007',
    text: 'SINGLE_CONTROL_DELETE_ERROR',
    statusCode: 422,
    http_status_text: 'UNPROCESSABLE_ENTITY',
    message: 'Error while deleting the single control',
    type: 'UleecoServerError',
    module: 'SINGLE_CONTROLS',
  },
  420008: {
    responseCode: '420008',
    text: 'SINGLE_CONTROL_DEVICE_ADD_ERROR',
    statusCode: 422,
    http_status_text: 'UNPROCESSABLE_ENTITY',
    message: 'Device already exists in another single group',
    type: 'UleecoClientError',
    module: 'SINGLE_CONTROLS',
  },
  420009: {
    responseCode: '420009',
    text: 'DEVICE_REFERENCES_ID_NOT_FOUND',
    statusCode: 422,
    http_status_text: 'UNPROCESSABLE_ENTITY',
    message: 'Device References Id Not Found ',
    type: 'UleecoClientError',
    module: 'SCHEDULES',
  },
  990001: {
    responseCode: '990001',
    text: 'ERROR_CREATING_ACTIVITY_LOGS',
    statusCode: 400,
    http_status_text: 'BAD_REQUEST',
    message: 'Error in Activity Log creation',
    type: 'UleecoServerError',
    module: 'ActivityLogs',
  },
  420000: {
    responseCode: '420000',
    text: 'ERROR_CODES_NOT_FOUND',
    statusCode: 422,
    http_status_text: 'NOT_FOUND',
    message: 'Error Codes Not Found',
    type: 'UleecoClientError',
    module: 'ERRORCODES',
  },
  430000: {
    responseCode: '430000',
    text: 'ERROR_WHILE_GETTING_THE_JOBS',
    statusCode: 422,
    http_status_text: 'NOT_FOUND',
    message: 'Error While Getting The Jobs',
    type: 'UleecoServerError',
    module: 'JOBS',
  },
  440000: {
    responseCode: '440000',
    text: 'INPUT_VALIDATION',
    statusCode: 400,
    http_status_text: 'BAD_REQUEST',
    message: 'Please check the input',
    type: 'UleecoClientError',
    module: 'InputValidation',
  },
  450000: {
    responseCode: '450000',
    text: 'GATEWAY_ALREADY_CONNECTED_TO_A_USER',
    statusCode: 422,
    http_status_text: 'UNPROCESSABLE_ENTITY',
    message: 'Gateway already connected to a user',
    type: 'UleecoClientError',
    module: 'DEVICES',
  },
  460000: {
    responseCode: '460000',
    text: 'CAMERA_DEVICE_NOT_FOUND',
    statusCode: 422,
    http_status_text: 'NOT_FOUND',
    message: 'Camera device not found',
    type: 'UleecoClientError',
    module: 'CAMERA_DEVICES',
  },
  460001: {
    responseCode: '460001',
    text: 'ERROR_WHILE_GETTING_CAMERA_DEVICES',
    statusCode: 422,
    http_status_text: 'UNPROCESSABLE_ENTITY',
    message: 'Error While Getting Camera Devices',
    type: 'UleecoServerError',
    module: 'CAMERA_DEVICES',
  },
  460002: {
    responseCode: '460002',
    text: 'CAMERA DEVICE NOT EXISTS',
    statusCode: 422,
    http_status_text: 'UNPROCESSABLE_ENTITY',
    message: 'Camera Device Not Exists',
    type: 'UleecoClientError',
    module: 'CAMERA_DEVICES',
  },
  460003: {
    responseCode: '460003',
    text: 'ERROR_WHILE_GETTING_HISTORY',
    statusCode: 422,
    http_status_text: 'UNPROCESSABLE_ENTITY',
    message: 'Error While Getting History',
    type: 'UleecoServerError',
    module: 'CAMERA_DEVICES',
  },
  470000: {
    responseCode: '470000',
    text: 'DEVICE_NOT_FOUND_IN_AWS_THINGGROUP',
    statusCode: 422,
    http_status_text: 'NOT_FOUND',
    message: 'Device Not Found in AWS ThingGroup ',
    type: 'UleecoClientError',
    module: 'DEVICES',
  },
  470001: {
    responseCode: '470001',
    text: 'DEVICE_REFERENCES_ID_NOT_FOUND',
    statusCode: 422,
    http_status_text: 'UNPROCESSABLE_ENTITY',
    message: 'Token Not Found',
    type: 'UleecoClientError',
    module: 'DEVICES',
  },
  470002: {
    responseCode: '470002',
    text: 'JSON_FILE_UNDEFINED',
    statusCode: 422,
    http_status_text: 'UNDEFINED',
    message: 'Please upload a JSON file',
    type: 'UleecoClientError',
    module: 'DEVICES',
  },
  470003: {
    responseCode: '470003',
    text: 'DEVICE_REFERENCES_DELETE_ERROR',
    statusCode: 422,
    http_status_text: 'UNPROCESSABLE_ENTITY',
    message: 'Error while deleting the device references record',
    type: 'UleecoServerError',
    module: 'DEVICES',
  },
  470004: {
    responseCode: '470004',
    text: 'OCCUPANTS_CAMERA_PERMISSIONS_NOT_ADDED',
    statusCode: 422,
    http_status_text: 'UNPROCESSABLE_ENTITY',
    message: 'Occupants Camera Permissions Not Added',
    type: 'UleecoServerError',
    module: 'OCCUPANT',
  },
  470005: {
    responseCode: '470005',
    text: 'CAMERA_DEVICE_NOT_FOUND',
    statusCode: 422,
    http_status_text: 'UNPROCESSABLE_ENTITY',
    message: 'Camera Device Not Found',
    type: 'UleecoClientError',
    module: 'OCCUPANT',
  },
  470006: {
    responseCode: '470006',
    text: 'OCCUPANTS_CAMERA_PERMISSIONS_ALREADY_EXISTS',
    statusCode: 422,
    http_status_text: 'UNPROCESSABLE_ENTITY',
    message: 'Occupants Camera Permissions Already Exist',
    type: 'UleecoClientError',
    module: 'OCCUPANT',
  },
  470007: {
    responseCode: '470007',
    text: 'OCCUPANTS_CAMERA_PERMISSIONS_RECORD_NOT_DELETED',
    statusCode: 422,
    http_status_text: 'UNPROCESSABLE_ENTITY',
    message: 'Occupants Camera Permissions Record Not Deleted',
    type: 'UleecoServerError',
    module: 'OCCUPANT',
  },
  470008: {
    responseCode: '470008',
    text: 'OCCUPANTS_CAMERA_PERMISSIONS_NOT_FOUND',
    statusCode: 422,
    http_status_text: 'UNPROCESSABLE_ENTITY',
    message: 'Occupants Camera Permissions Not Found',
    type: 'UleecoClientError',
    module: 'OCCUPANT',
  },
  470009: {
    responseCode: '470009',
    text: 'CAMERA_DEVICE_NOT_UPDATED',
    statusCode: 422,
    http_status_text: 'UNPROCESSABLE_ENTITY',
    message: 'Camera Devices Not Updated',
    type: 'UleecoServerError',
    module: 'DEVICES',
  },
  470010: {
    responseCode: '470010',
    text: 'CAMERA_DEVICE_GATEWAY_ALREADY_EXISTS',
    statusCode: 422,
    http_status_text: 'UNPROCESSABLE_ENTITY',
    message: 'Camera Devices Gateway Already Exists',
    type: 'UleecoClientError',
    module: 'DEVICES',
  },
  470011: {
    responseCode: '470011',
    text: 'PLAN LIMITATION',
    statusCode: 422,
    http_status_text: 'UNPROCESSABLE_ENTITY',
    message: 'The Count of Cameras Exceeds the Plan Limit',
    type: 'UleecoClientError',
    module: 'DEVICES',
  },
  470012: {
    responseCode: '470012',
    text: 'PLAN_CODE_NOT_FOUND',
    statusCode: 422,
    http_status_text: 'UNPROCESSABLE_ENTITY',
    message: 'Plan Code Not Found For The Gateway',
    type: 'UleecoClientError',
    module: 'DEVICES',
  },
  480000: {
    responseCode: '480000',
    text: 'CAMERA_DELETE_ERROR',
    statusCode: 404,
    http_status_text: 'NOT_FOUND',
    message: 'Camera device not found to delete',
    type: 'UleecoClientError',
    module: 'CAMERA_DELETE',
  },
  490000: {
    responseCode: '490000',
    text: 'REDSHIFT_DELETE_DEVICE_HISTORY_ERROR',
    statusCode: 422,
    http_status_text: 'UNPROCESSABLE_ENTITY',
    message: 'Redshift Device History Not Deleted',
    type: 'UleecoServerError',
    module: 'REDSHIFT_DELETE',
  },
  490001: {
    responseCode: '490001',
    text: 'SINGLE_CONTROL_GATEWAY_RECORD_NOT_FOUND_ERROR',
    statusCode: 422,
    http_status_text: 'UNPROCESSABLE_ENTITY',
    message: 'Single Control Gateway Record Not Found',
    type: 'UleecoClientError',
    module: 'SINGLE_CONTROLS',
  },
  490002: {
    responseCode: '490002',
    text: 'ERROR_WHILE_GETTING_OCCUPANTS_CAMERA_PERMISSIONS',
    statusCode: 422,
    http_status_text: 'UNPROCESSABLE_ENTITY',
    message: 'Error While Getting Occupants Camera Permissions',
    type: 'UleecoServerError',
    module: 'OCCUPANT',
  },
  490003: {
    responseCode: '490003',
    text: 'ERROR_WHILE_GETTING_OCCUPANTS_PERMISSIONS',
    statusCode: 422,
    http_status_text: 'UNPROCESSABLE_ENTITY',
    message: 'Error While Getting Occupants Permissions',
    type: 'UleecoServerError',
    module: 'OCCUPANT',
  },
  490004: {
    responseCode: '490004',
    text: 'COORDINATOR_DEVICE_CANNOT_BE_ADDED',
    statusCode: 422,
    http_status_text: 'UNPROCESSABLE_ENTITY',
    message: 'Coordinator Device cannot be Added',
    type: 'UleecoClientError',
    module: 'DEVICES',
  },
  510001: {
    responseCode: '510001',
    text: 'CATEGORY_ADD_ERROR',
    statusCode: 422,
    http_status_text: 'UNPROCESSABLE_ENTITY',
    message: 'Error while adding the category',
    type: 'UleecoServerError',
    module: 'CATEGORIES',
  },
  510002: {
    responseCode: '510002',
    text: 'CATEGORY_GET_ERROR',
    statusCode: 422,
    http_status_text: 'UNPROCESSABLE_ENTITY',
    message: 'Error while getting the category',
    type: 'UleecoServerError',
    module: 'CATEGORIES',
  },
  510003: {
    responseCode: '510003',
    text: 'CATEGORY_UPDATE_ERROR',
    statusCode: 422,
    http_status_text: 'UNPROCESSABLE_ENTITY',
    message: 'Error while updating the category',
    type: 'UleecoServerError',
    module: 'CATEGORIES',
  },
});

export default ErrorCodes;
